version: 0.0
os: linux
files:
  - source: build_output
    destination: /home/ubuntu/aspnetcoreapp
  - source: build/scripts/virtualhost.conf
    destination: /home/ubuntu/aspnetcoreapp
hooks:
  ApplicationStop:
    - location: build/scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: build/scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: build/scripts/install_dotnetcore
      timeout: 500
      runas: root

    - location: build/scripts/install_httpd
      timeout: 300
      runas: root

  ApplicationStart:
    - location: build/scripts/start_service
      timeout: 300
      runas: root
