version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore SimpleCustomerApp.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output SimpleCustomerApp.csproj
artifacts:
  files:
    - SimpleCustomerApp/build_output/**/*
    - scripts/**/*
    - appspec.yml